# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:11.6.0

pipelines:
  default:
    - step:
       caches:
         - node
       script:
         # Bitbuck reop branch 에서 커밋메시지 추출
         - echo "# Gathering commit message\n"
         - bitbuckCommitMessage=$(git log -1 --pretty=%B)
         - echo " > $bitbuckCommitMessage"
         #Vuepress 추가
         - yarn global add vuepress@next
         - yarn add -D vuepress@next
         #Vuepress 빌드
         - yarn src:build 
         - ls src/.vuepress/dist -al
         ##Github(GitHub Pages repository) 로 보내기
         # dist 디렉토리 git 프로젝트로 초기화
         # - git init
         # GitHub 원격저장소 연결
         - git remote set-url origin https://andrewlee1228:Math2028@github.com/AndrewLee1228/AndrewLee1228.github.io.git
         - git remote update
         - git fetch
         - git checkout -b gh-pages
         # 최신 gh-pages 브랜치 정보를 가져와 rebase를 진행한다.
         - git pull origin gh-pages --rebase
         # Vuepress build로 생긴 src/.vuepress/dist 폴더 아래 모든 정보를 현재 위치로 가져온다.
         - cp -R src/.vuepress/dist/* .
         # node_modules폴더와 src/.vuepress/dist 폴더를 지워준다.
         - git clean -fx node_modules
         - git clean -fx src/.vuepress/dist
         # add & commit 
         - git add .
         - git commit -a -m "$bitbuckCommitMessage"
         # gh-pages 브랜치에 PUSH!
         - git push origin gh-pages
         
         




